=== FrameworkSystemsGmbH/PBE/src/PBE/PBE.dtd
<!ELEMENT PBE (FSVersions?,Params,Sequence)>
<!ATTLIST PBE Logfile CDATA "">
<!ATTLIST PBE Logarchive CDATA "">

<!ELEMENT FSVersions (FSVersion*)>
<!ELEMENT FSVersion EMPTY>
<!ATTLIST FSVersion FS (5.0.0.0|4.6.0.0|4.5.0.0|4.4.0.0|4.3.0.0|4.2.0.0|4.0.0.0|3.11.0.0|3.10.0.0|3.9.0.0|3.8.0.0|3.7.0.0|3.6.0.0|3.5.0.0|3.4.0.0|3.3.0.0|3.2.0.0) #REQUIRED>
<!ATTLIST FSVersion Dir CDATA #REQUIRED>

<!ELEMENT Params (Param*)>
<!ELEMENT Param EMPTY>
<!ATTLIST Param Name CDATA #REQUIRED>
<!ATTLIST Param Value CDATA #REQUIRED>

<!ELEMENT Sequence ((Batch|FSConsole|Sequence|Parallel|Condition|CompileRun|Export|ApprovedExport|Import|ApprovedImport|Publish|Publish2Go|Publish4Cloud|ExportDoc|MD|RD)*)>
<!ATTLIST Sequence Name CDATA "">

<!ELEMENT Condition ((Batch|FSConsole|Sequence|Parallel|Condition|CompileRun|Export|ApprovedExport|Import|ApprovedImport|Publish|Publish2Go|Publish4Cloud|ExportDoc|MD|RD)*)>
<!ATTLIST Condition Name CDATA "">
<!ATTLIST Condition Value CDATA #REQUIRED>
<!ATTLIST Condition Equals CDATA #REQUIRED>

<!ELEMENT Parallel ((Batch|FSConsole|Sequence|Parallel|Condition|CompileRun|Export|ApprovedExport|Import|ApprovedImport|Publish|Publish2Go|Publish4Cloud|ExportDoc|MD|RD|ImportQueue)*)>
<!ATTLIST Parallel Name CDATA "">
<!ATTLIST Parallel MaxTasks CDATA "">

<!ELEMENT Batch (Args?)>
<!ATTLIST Batch Name CDATA "">
<!ATTLIST Batch Cmd CDATA #REQUIRED>
<!ATTLIST Batch Directory CDATA "">
<!ATTLIST Batch Args CDATA "">

<!ELEMENT Args (Arg*)>
<!ELEMENT Arg (#PCDATA)>

<!ELEMENT FSConsole (Args?)>
<!ATTLIST FSConsole Name CDATA "">
<!ATTLIST FSConsole FS (5.0.0.0|4.6.0.0|4.5.0.0|4.4.0.0|4.3.0.0|4.2.0.0|4.0.0.0|3.11.0.0|3.10.0.0|3.9.0.0|3.8.0.0|3.7.0.0|3.6.0.0|3.5.0.0|3.4.0.0|3.3.0.0|3.2.0.0) #REQUIRED>
<!ATTLIST FSConsole Rep CDATA #REQUIRED>
<!ATTLIST FSConsole Args CDATA #REQUIRED>

<!ELEMENT CompileRun EMPTY>
<!ATTLIST CompileRun Name CDATA "">
<!ATTLIST CompileRun FS (5.0.0.0|4.6.0.0|4.5.0.0|4.4.0.0|4.3.0.0|4.2.0.0|4.0.0.0|3.11.0.0|3.10.0.0|3.9.0.0|3.8.0.0|3.7.0.0|3.6.0.0|3.5.0.0|3.4.0.0|3.3.0.0|3.2.0.0) #REQUIRED>
<!ATTLIST CompileRun Rep CDATA #REQUIRED>
<!ATTLIST CompileRun Run CDATA #REQUIRED>
<!ATTLIST CompileRun MaxParallel CDATA "">
<!ATTLIST CompileRun DeleteCompileDir (0|1) #IMPLIED>

<!ELEMENT Export EMPTY>
<!ATTLIST Export Name CDATA "">
<!ATTLIST Export FS (5.0.0.0|4.6.0.0|4.5.0.0|4.4.0.0|4.3.0.0|4.2.0.0|4.0.0.0|3.11.0.0|3.10.0.0|3.9.0.0|3.8.0.0|3.7.0.0|3.6.0.0|3.5.0.0|3.4.0.0|3.3.0.0|3.2.0.0) #REQUIRED>
<!ATTLIST Export Rep CDATA #REQUIRED>
<!ATTLIST Export Package CDATA #REQUIRED>
<!ATTLIST Export Version CDATA #REQUIRED>
<!ATTLIST Export Queue CDATA "">
<!ATTLIST Export Mode CDATA #FIXED "Bugfix">
<!ATTLIST Export Dir CDATA "">
<!ATTLIST Export IncludeBasePackages (ServiceRelease|Unsealed|All) #IMPLIED>

<!ELEMENT ApprovedExport EMPTY>
<!ATTLIST ApprovedExport Name CDATA "">
<!ATTLIST ApprovedExport FS (5.0.0.0|4.6.0.0|4.5.0.0|4.4.0.0|4.3.0.0|4.2.0.0|4.0.0.0|3.11.0.0|3.10.0.0|3.9.0.0|3.8.0.0|3.7.0.0|3.6.0.0|3.5.0.0|3.4.0.0|3.3.0.0|3.2.0.0) #REQUIRED>
<!ATTLIST ApprovedExport Rep CDATA #REQUIRED>
<!ATTLIST ApprovedExport Package CDATA #REQUIRED>
<!ATTLIST ApprovedExport Version CDATA #REQUIRED>
<!ATTLIST ApprovedExport Mode CDATA #FIXED "Bugfix">
<!ATTLIST ApprovedExport Dir CDATA "">
<!ATTLIST ApprovedExport IncludeBasePackages (ServiceRelease|Unsealed|All) #IMPLIED>

<!ELEMENT Import EMPTY>
<!ATTLIST Import Name CDATA "">
<!ATTLIST Import FS (5.0.0.0|4.6.0.0|4.5.0.0|4.4.0.0|4.3.0.0|4.2.0.0|4.0.0.0|3.11.0.0|3.10.0.0|3.9.0.0|3.8.0.0|3.7.0.0|3.6.0.0|3.5.0.0|3.4.0.0|3.3.0.0|3.2.0.0) #REQUIRED>
<!ATTLIST Import Rep CDATA #REQUIRED>
<!ATTLIST Import Package CDATA #REQUIRED>
<!ATTLIST Import Version CDATA #REQUIRED>
<!ATTLIST Import Mode CDATA #FIXED "Bugfix">
<!ATTLIST Import Dir CDATA "">

<!ELEMENT ImportQueue EMPTY>
<!ATTLIST ImportQueue Name CDATA "">
<!ATTLIST ImportQueue Rep CDATA #REQUIRED>
<!ATTLIST ImportQueue QueueName CDATA #REQUIRED>

<!ELEMENT ApprovedImport EMPTY>
<!ATTLIST ApprovedImport Name CDATA "">
<!ATTLIST ApprovedImport Rep CDATA #REQUIRED>
<!ATTLIST ApprovedImport Dir CDATA "">
<!ATTLIST ApprovedImport HistoryDir CDATA "">

<!ELEMENT Publish EMPTY>
<!ATTLIST Publish Name CDATA "">
<!ATTLIST Publish FS (5.0.0.0|4.6.0.0|4.5.0.0|4.4.0.0|4.3.0.0|4.2.0.0|4.0.0.0|3.11.0.0|3.10.0.0|3.9.0.0|3.8.0.0|3.7.0.0|3.6.0.0|3.5.0.0|3.4.0.0|3.3.0.0|3.2.0.0) #REQUIRED>
<!ATTLIST Publish Rep CDATA #REQUIRED>
<!ATTLIST Publish Package CDATA #REQUIRED>
<!ATTLIST Publish Version CDATA #REQUIRED>
<!ATTLIST Publish Setting CDATA #REQUIRED>

<!ELEMENT Publish2Go EMPTY>
<!ATTLIST Publish2Go Name CDATA "">
<!ATTLIST Publish2Go FS (5.0.0.0|4.6.0.0|4.5.0.0|4.4.0.0|4.3.0.0|4.2.0.0|4.0.0.0|3.11.0.0) #REQUIRED>
<!ATTLIST Publish2Go Rep CDATA #REQUIRED>
<!ATTLIST Publish2Go Package CDATA #REQUIRED>
<!ATTLIST Publish2Go Version CDATA #REQUIRED>
<!ATTLIST Publish2Go Setting CDATA #REQUIRED>

<!ELEMENT Publish4Cloud EMPTY>
<!ATTLIST Publish4Cloud Name CDATA "">
<!ATTLIST Publish4Cloud FS (5.0.0.0|4.6.0.0|4.5.0.0|4.4.0.0|4.3.0.0) #REQUIRED>
<!ATTLIST Publish4Cloud Rep CDATA #REQUIRED>
<!ATTLIST Publish4Cloud Package CDATA #REQUIRED>
<!ATTLIST Publish4Cloud Version CDATA #REQUIRED>
<!ATTLIST Publish4Cloud Setting CDATA #REQUIRED>

<!ELEMENT ExportDoc (Args?)>
<!ATTLIST ExportDoc Name CDATA "">
<!ATTLIST ExportDoc FS (5.0.0.0|4.6.0.0|4.5.0.0|4.4.0.0|4.3.0.0|4.2.0.0|4.0.0.0|3.11.0.0) #REQUIRED>
<!ATTLIST ExportDoc Rep CDATA #REQUIRED>
<!ATTLIST ExportDoc Package CDATA #REQUIRED>
<!ATTLIST ExportDoc Version CDATA #REQUIRED>
<!ATTLIST ExportDoc Iso CDATA #REQUIRED>
<!ATTLIST ExportDoc ExportDBTables CDATA #FIXED "1">
<!ATTLIST ExportDoc Dir CDATA "">
<!ATTLIST ExportDoc Args CDATA "">
<!ATTLIST ExportDoc UseLicense CDATA #FIXED "1">
<!ATTLIST ExportDoc Setting CDATA "">

<!ELEMENT MD EMPTY>
<!ATTLIST MD Name CDATA "">
<!ATTLIST MD Dir CDATA #REQUIRED>

<!ELEMENT RD EMPTY>
<!ATTLIST RD Name CDATA "">
<!ATTLIST RD Dir CDATA #REQUIRED>

=== FrameworkSystemsGmbH/PBE/src/PBE/PBE.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE PBE SYSTEM "PBE.dtd">
<PBE Logfile="C:\temp\Log.html" Logarchive="C:\temp\Archive\Log_{DateTime}.html">
  <FSVersions>
    <FSVersion FS="4.7.0.0" Dir="C:\Programme\enventa Group\Framework Studio\4.7" />
  </FSVersions>

  <Params>
    <Param Name="ExportDir" Value="E:\temp\export\" />
    <Param Name="rep1" Value="\ConnectionType SqlServer \Server NV261 \Database FSDemo37" />
    <Param Name="rep2" Value="\ConnectionType SqlServer \Server NV261 \Database FSDemo37Imp" />
  </Params>

  <Sequence>
    <RD Name="letztes Export-Dir löschen" Dir="{ExportDir}" />
    <MD Name="Export-Dir neu anlegen" Dir="{ExportDir}" />

    <Parallel Name="Compile Repository 1">
      <ImportQueue QueueName="ImportQueue" Rep="{rep2}" />

      <Sequence Name="Compile-Lauf FS 3.7">
        <CompileRun FS="3.7.0.0" Rep="{rep1}" Run="1" />

        <Export FS="3.7.0.0" Rep="{rep1}" Package="Cust1" Version="3.2" Queue="ImportQueue" />
        <Export FS="3.7.0.0" Rep="{rep1}" Package="Cust2" Version="3.2" Queue="ImportQueue" />
      </Sequence>

      <Sequence Name="Compile-Lauf FS 3.8">
        <CompileRun FS="3.8.0.0" Rep="{rep1}" Run="1" />

        <Export FS="3.8.0.0" Rep="{rep1}" Package="Cust1" Version="3.3" Queue="ImportQueue" />
        <Export FS="3.8.0.0" Rep="{rep1}" Package="Cust2" Version="3.3" Queue="ImportQueue" />
      </Sequence>
    </Parallel>

    <Parallel Name="Compile Repository 2">
      <CompileRun FS="3.7.0.0" Rep="{rep2}" Run="1" />
      <CompileRun FS="3.8.0.0" Rep="{rep2}" Run="1" />

      <Condition Name="Sonntags-Compile" Value="{Weekday}" Equals="So">
        <Parallel>
          <CompileRun FS="3.7.0.0" Rep="{rep2}" Run="Sonntag" />
          <CompileRun FS="3.8.0.0" Rep="{rep2}" Run="Sonntag" />
        </Parallel>
      </Condition>
    </Parallel>

    <Sequence Name="Publish">
      <Batch Name="IIS beenden" Cmd="NET" Args="STOP W3SVC" />

      <Parallel Name="Publish" MaxTasks="2">
        <Publish FS="3.7.0.0" Rep="{rep1}" Package="Cust1" Version="3.2"
                 Setting="Cust1_Setting1" />
        <Publish FS="3.7.0.0" Rep="{rep1}" Package="Cust1" Version="3.2"
                 Setting="Cust1_Setting2" />
        <Publish FS="3.7.0.0" Rep="{rep1}" Package="Cust2" Version="3.2"
                 Setting="Cust2_Demo" />
      </Parallel>

      <Batch Name="IIS wieder starten" Cmd="NET" Args="Start W3SVC" />
    </Sequence>
  </Sequence>
</PBE>
